### PR TITLE
additional pass on correct patterns

### PR DESCRIPTION
**Pull request by benjaminbollen**
- delayed recovery improved re-entrancy pattern for `executeRecovery`
- `TransferRule` is superseded by `TokenRules.directTransfers`
- `TokenRules._executeTransfers` improved re-entrancy pattern by early setting `transfersAllowed` to false

### CODE REVIEW

**Comment by benjaminbollen** [comment]
addresses #173

**Comment by benjaminbollen** [comment]
github doesnt pick up currently on the PR runs

https://www.travis-ci.org/OpenST/openst-contracts/builds/507938205

**Comment by benjaminbollen** [comment]
PR run 
https://www.travis-ci.org/OpenST/openst-contracts/builds/507939765

**Comment by benjaminbollen** [comment]
it does pick it up, im just impatient ...

**Comment by gulshanvasnani** [comment]
> it does pick it up, im just impatient ...

It sometimes takes time to start the tests.

**Pull request merged**
